name: ARC4 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ARC4

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        ./utils/arc/monc_compile_arc.sh
    - name: run
      run: |
        ./utils/arc/submonc.sge
